test:
  script:
  - export DATABASE_URL=postgres://xvcvmtghoxawjg:fa1e4144be6d88ee991f6bb9b35a9f2bae55dc42541b4f7d8e63aec2313b0c19@ec2-54-221-192-231.compute-1.amazonaws.com:5432/d70mlirihnovou
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install -r requirements.txt
  - python manage.py test

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
